In [70]:
import matplotlib as plt
import numpy as np
import pandas as pd

from joblib import load

logreg_import3deg = load('logreg_poly.joblib')

In [113]:
race1 = pd.read_csv('/Users/mk2/Downloads/race10 - Sheet1.csv',index_col=[0,1])

In [114]:
#race2 = pd.read_csv('/Users/mk2/Downloads/race6 - Sheet1 (7).csv',index_col=[0,1])

In [115]:
#race3 = pd.read_csv('/Users/mk2/Downloads/race7 - Sheet1 (4).csv',index_col=[0,1])

In [116]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([

    ('poly', PolynomialFeatures(degree=6, interaction_only=False, include_bias=True, order='C')),
    
    ("std_scaler1", StandardScaler(copy=True, with_mean=True, with_std=True)),
    
       
])  

In [117]:
race_fit3 = num_pipeline.fit_transform(race1)
#race_fit4 = num_pipeline.fit_transform(race2)
#race_fit5 = num_pipeline.fit_transform(race3)

In [118]:
logreg_import3deg.predict(race_fit3)

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [119]:
logreg_import3deg.predict(race_fit4)

array([1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0])

In [105]:
logreg_import3deg.predict(race_fit5)

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1])

In [78]:
logreg_import3deg.predict(race_fit3)

array([0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0])

In [61]:
logreg_import3deg.predict(race_fit4)

array([0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0])

In [50]:
logreg_import.fit(poly_std_train,train_label1)

/Users/mk2/opt/anaconda3/envs/no_base/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression(class_weight='balanced', max_iter=1000000, tol=1e-07)

In [51]:
hisgra_import.fit(poly_std_train,train_label1)

/Users/mk2/opt/anaconda3/envs/no_base/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


HistGradientBoostingClassifier()

In [52]:
predictions_deg6_hist = hisgra_import.predict(poly_std_test)

In [53]:
predictions_deg6 = logreg_import.predict(poly_std_test)

In [54]:
confusion_matrix(predictions_deg3,test_label1)

array([[10363,  1411],
       [ 1163,  2207]])

In [55]:
confusion_matrix(predictions_deg3_hist,test_label1)

array([[10177,  3107],
       [ 1349,   511]])

In [56]:
confusion_matrix(predictions_deg6,test_label1)

array([[7352, 1373],
       [4174, 2245]])

In [57]:
confusion_matrix(predictions_deg6_hist,test_label1)

array([[10845,  3099],
       [  681,   519]])